server:
  port: 8443
#  When the port is set to 0, the server starts on a randomly chosen available port.
#  This is useful when running automated integration tests to ensure that
#  any concurrently running tests do not clash on a hard-coded port number.
#  port: 0
#  ssl:  # Enable HTTPS in the embedded server
#    key-store: classpath:keystore/tacocloud.p12
#    key-password: password
#    key-store-password: password
#    key-store-type: PKCS12

logging:  # dev purposes
  level:
    tacos: DEBUG
#    # write the log entries to the file taco-cloud.log at /var/logs/
#    # Log files rotate once they reach 10 MB in size by default.
#    file:
#      path: /var/logs/taco-cloud.log

# Using special property values
# greeting:
#   welcome: You are using ${spring.application.name}.

taco:
  orders:
    page-size: 10

