spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopass
#  sql:
#    init:
#      schema-locations:
#        - order-schema.sql
#        - ingredient-schema.sql
#        - taco-schema.sql
#        - user-schema.sql
#      data-locations:
#        - ingredients.sql

logging:
  level:
    tacos: WARN